//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMTInterfaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsfSales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsfSales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaleMTInterfaces.Properties.rsfSales", typeof(rsfSales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng không được để trống !.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mật khẩu !.
        /// </summary>
        internal static string Authentication1 {
            get {
                return ResourceManager.GetString("Authentication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng !.
        /// </summary>
        internal static string Authentication2 {
            get {
                return ResourceManager.GetString("Authentication2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có sản phẩm nào !.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn hủy đơn hàng hiện tại ?.
        /// </summary>
        internal static string Sale1 {
            get {
                return ResourceManager.GetString("Sale1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng chưa thanh toán bạn có chắc chắn muốn đóng ?.
        /// </summary>
        internal static string Sale2 {
            get {
                return ResourceManager.GetString("Sale2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ hàng để bán !.
        /// </summary>
        internal static string Sale3 {
            get {
                return ResourceManager.GetString("Sale3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập tối thiểu 4 ký tự !.
        /// </summary>
        internal static string Sale4 {
            get {
                return ResourceManager.GetString("Sale4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ được chiết khấu một trong hai loại theo % hoặc theo số tiền !.
        /// </summary>
        internal static string SpecialDiscount {
            get {
                return ResourceManager.GetString("SpecialDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập giá trị chiết khấu !.
        /// </summary>
        internal static string SpecialDiscount1 {
            get {
                return ResourceManager.GetString("SpecialDiscount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn người chiết khấu !.
        /// </summary>
        internal static string SpecialDiscount2 {
            get {
                return ResourceManager.GetString("SpecialDiscount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập ghi chú cho chiết khấu !.
        /// </summary>
        internal static string SpecialDiscount3 {
            get {
                return ResourceManager.GetString("SpecialDiscount3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng hoặc mật khẩu không đúng !.
        /// </summary>
        internal static string SpecialDiscount4 {
            get {
                return ResourceManager.GetString("SpecialDiscount4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiết khấu tối đa không được quá .
        /// </summary>
        internal static string SpecialDiscount5 {
            get {
                return ResourceManager.GetString("SpecialDiscount5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền chiết khấu không được lớn hơn tổng số tiền của hóa đơn !.
        /// </summary>
        internal static string SpecialDiscount6 {
            get {
                return ResourceManager.GetString("SpecialDiscount6", resourceCulture);
            }
        }
    }
}
