//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMTInterfaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsfInvoicePayment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsfInvoicePayment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaleMTInterfaces.Properties.rsfInvoicePayment", typeof(rsfInvoicePayment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anh/chị có muốn xóa dữ liệu này không?.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thành công.
        /// </summary>
        internal static string DeleteOK {
            get {
                return ResourceManager.GetString("DeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền trên lưới chưa đúng với số tiền bạn nhập..
        /// </summary>
        internal static string SavePaymentDif1 {
            get {
                return ResourceManager.GetString("SavePaymentDif1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại số tiền hoặc phân bổ lại số tiền..
        /// </summary>
        internal static string SavePaymentDif2 {
            get {
                return ResourceManager.GetString("SavePaymentDif2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thành công.
        /// </summary>
        internal static string SavePaymentOK {
            get {
                return ResourceManager.GetString("SavePaymentOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số tiền thanh toán..
        /// </summary>
        internal static string SavePaymentZero {
            get {
                return ResourceManager.GetString("SavePaymentZero", resourceCulture);
            }
        }
    }
}
