//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMTInterfaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsfSales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsfSales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaleMTInterfaces.Properties.rsfSales", typeof(rsfSales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng không được để trống..
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mật khẩu..
        /// </summary>
        internal static string Authentication1 {
            get {
                return ResourceManager.GetString("Authentication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng..
        /// </summary>
        internal static string Authentication2 {
            get {
                return ResourceManager.GetString("Authentication2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng .
        /// </summary>
        internal static string Authentication3 {
            get {
                return ResourceManager.GetString("Authentication3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng {0} không có quyền thay đổi giá sản phẩm..
        /// </summary>
        internal static string Authentication4 {
            get {
                return ResourceManager.GetString("Authentication4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng {0} không có quyền chiết khấu..
        /// </summary>
        internal static string Authentication5 {
            get {
                return ResourceManager.GetString("Authentication5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn bảng giá..
        /// </summary>
        internal static string BarCode1 {
            get {
                return ResourceManager.GetString("BarCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vạch không hợp lệ..
        /// </summary>
        internal static string BarCode2 {
            get {
                return ResourceManager.GetString("BarCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm không có thông tin mã vạch..
        /// </summary>
        internal static string BarCode3 {
            get {
                return ResourceManager.GetString("BarCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu xuất Excel..
        /// </summary>
        internal static string BarCode4 {
            get {
                return ResourceManager.GetString("BarCode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập thông tin nhận tiền từ đâu..
        /// </summary>
        internal static string CastPayment {
            get {
                return ResourceManager.GetString("CastPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số tiền..
        /// </summary>
        internal static string CastPayment1 {
            get {
                return ResourceManager.GetString("CastPayment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn dòng trước khi xóa..
        /// </summary>
        internal static string CastPayment4 {
            get {
                return ResourceManager.GetString("CastPayment4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn hủy sử dụng phiếu giảm giá..
        /// </summary>
        internal static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu giảm giá không tồn tại..
        /// </summary>
        internal static string Coupon1 {
            get {
                return ResourceManager.GetString("Coupon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu giảm giá đã được sử dụng..
        /// </summary>
        internal static string Coupon2 {
            get {
                return ResourceManager.GetString("Coupon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu giảm giá chưa thể sử dụng..
        /// </summary>
        internal static string Coupon3 {
            get {
                return ResourceManager.GetString("Coupon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu giảm giá đã ngưng sử dụng..
        /// </summary>
        internal static string Coupon4 {
            get {
                return ResourceManager.GetString("Coupon4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công..
        /// </summary>
        internal static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công..
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        internal static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn khách hàng..
        /// </summary>
        internal static string ItemReturn {
            get {
                return ResourceManager.GetString("ItemReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn đơn hàng trả lại..
        /// </summary>
        internal static string ItemReturn1 {
            get {
                return ResourceManager.GetString("ItemReturn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập thông tin phản hồi..
        /// </summary>
        internal static string ItemReturn3 {
            get {
                return ResourceManager.GetString("ItemReturn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật. Dữ liệu đã được bàn giao ca..
        /// </summary>
        internal static string ItemReturn4 {
            get {
                return ResourceManager.GetString("ItemReturn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anh/Chị có muốn xóa dữ liệu này không ?.
        /// </summary>
        internal static string ItemReturn5 {
            get {
                return ResourceManager.GetString("ItemReturn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công , chương trình sẽ khởi động lại cho chính xác..
        /// </summary>
        internal static string Login1 {
            get {
                return ResourceManager.GetString("Login1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo .
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu cần tìm..
        /// </summary>
        internal static string NotItem {
            get {
                return ResourceManager.GetString("NotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thông tin thành công, chương trình sẽ được đóng lại để điều chỉnh thông số, vui lòng mở lại chương trình.
        /// </summary>
        internal static string OptionData1 {
            get {
                return ResourceManager.GetString("OptionData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền thanh toán không được lớn hơn số dư hiện tại..
        /// </summary>
        internal static string Payment1 {
            get {
                return ResourceManager.GetString("Payment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã quà tặng không tồn tại..
        /// </summary>
        internal static string Payment2 {
            get {
                return ResourceManager.GetString("Payment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu quà tặng chưa được kích hoạt..
        /// </summary>
        internal static string Payment3 {
            get {
                return ResourceManager.GetString("Payment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu quà tặng đã được sử dụng..
        /// </summary>
        internal static string Payment4 {
            get {
                return ResourceManager.GetString("Payment4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu quà tặng không thể sử dụng thanh toán cho các mặt hàng hiện tại !.
        /// </summary>
        internal static string Payment5 {
            get {
                return ResourceManager.GetString("Payment5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng sản phẩm khuyến mại của chương trình {0} không được lớn hơn số lượng quy định..
        /// </summary>
        internal static string Promotion1 {
            get {
                return ResourceManager.GetString("Promotion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng sản phẩm khuyến mại của chương trình {0} không được nhỏ hơn số lượng quy định..
        /// </summary>
        internal static string Promotion3 {
            get {
                return ResourceManager.GetString("Promotion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho sản phẩm có mã {0} không đủ để xuất khuyến mại..
        /// </summary>
        internal static string Promotion4 {
            get {
                return ResourceManager.GetString("Promotion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình {0} phải chọn 1 trong 2 danh sách..
        /// </summary>
        internal static string Promotion5 {
            get {
                return ResourceManager.GetString("Promotion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anh/Chị có muốn xóa dữ liệu này không ?.
        /// </summary>
        internal static string QuestionDelete {
            get {
                return ResourceManager.GetString("QuestionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên công ty in hóa đơn..
        /// </summary>
        internal static string RedBill {
            get {
                return ResourceManager.GetString("RedBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã số thuế in hóa đơn không ít hơn 10 và nhỏ hơn 15 ký tự..
        /// </summary>
        internal static string RedBill1 {
            get {
                return ResourceManager.GetString("RedBill1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ công ty in hóa đơn không ít hơn 10 ký tự..
        /// </summary>
        internal static string RedBill2 {
            get {
                return ResourceManager.GetString("RedBill2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu bán hàng..
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn hủy thông tin bán hàng hay không ?.
        /// </summary>
        internal static string Sale1 {
            get {
                return ResourceManager.GetString("Sale1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn đóng màn hình bán hàng ?.
        /// </summary>
        internal static string Sale2 {
            get {
                return ResourceManager.GetString("Sale2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng không đủ số lượng bán.
        /// </summary>
        internal static string Sale3 {
            get {
                return ResourceManager.GetString("Sale3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ít nhất 4 ký tự.
        /// </summary>
        internal static string Sale4 {
            get {
                return ResourceManager.GetString("Sale4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn thông tin khách hàng trước..
        /// </summary>
        internal static string Sale5 {
            get {
                return ResourceManager.GetString("Sale5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thành công..
        /// </summary>
        internal static string Sale6 {
            get {
                return ResourceManager.GetString("Sale6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đủ tiền thanh toán cho hóa đơn này..
        /// </summary>
        internal static string Sale7 {
            get {
                return ResourceManager.GetString("Sale7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm nào..
        /// </summary>
        internal static string Sale8 {
            get {
                return ResourceManager.GetString("Sale8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy cổng COM !.
        /// </summary>
        internal static string SCom {
            get {
                return ResourceManager.GetString("SCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anh/Chị có muốn kết ca làm việc không ?.
        /// </summary>
        internal static string Shift1 {
            get {
                return ResourceManager.GetString("Shift1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anh/Chị có muốn chuyển ca làm việc tiếp theo không ?.
        /// </summary>
        internal static string Shift2 {
            get {
                return ResourceManager.GetString("Shift2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ được chiết khấu một trong hai loại theo % hoặc theo số tiền..
        /// </summary>
        internal static string SpecialDiscount {
            get {
                return ResourceManager.GetString("SpecialDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anh/chị vui lòng nhập giá trị chiết khấu..
        /// </summary>
        internal static string SpecialDiscount1 {
            get {
                return ResourceManager.GetString("SpecialDiscount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn người chiết khấu..
        /// </summary>
        internal static string SpecialDiscount2 {
            get {
                return ResourceManager.GetString("SpecialDiscount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập ghi chú cho chiết khấu..
        /// </summary>
        internal static string SpecialDiscount3 {
            get {
                return ResourceManager.GetString("SpecialDiscount3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng hoặc mật khẩu không đúng..
        /// </summary>
        internal static string SpecialDiscount4 {
            get {
                return ResourceManager.GetString("SpecialDiscount4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng {0} chỉ có quyền chiết khấu với số tiền nhỏ hơn hoặc bằng {1} VNĐ..
        /// </summary>
        internal static string SpecialDiscount5 {
            get {
                return ResourceManager.GetString("SpecialDiscount5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền chiết khấu không được lớn hơn tổng số tiền của hóa đơn..
        /// </summary>
        internal static string SpecialDiscount6 {
            get {
                return ResourceManager.GetString("SpecialDiscount6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng {0} chỉ có quyền chiết khấu % nhỏ hơn hoặc bằng {1} %..
        /// </summary>
        internal static string SpecialDiscount7 {
            get {
                return ResourceManager.GetString("SpecialDiscount7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có sản phẩm cho chiết khấu này..
        /// </summary>
        internal static string SpecialDiscount8 {
            get {
                return ResourceManager.GetString("SpecialDiscount8", resourceCulture);
            }
        }
    }
}
