//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMTInterfaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsfUtilities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsfUtilities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaleMTInterfaces.Properties.rsfUtilities", typeof(rsfUtilities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công..
        /// </summary>
        internal static string GoodInventory {
            get {
                return ResourceManager.GetString("GoodInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anh/Chị có muốn lưu dữ liệu này không ?.
        /// </summary>
        internal static string GoodInventory1 {
            get {
                return ResourceManager.GetString("GoodInventory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập kiểm kê cho tất cả các sản phẩm trước khi nhập điều chỉnh..
        /// </summary>
        internal static string GoodInventory2 {
            get {
                return ResourceManager.GetString("GoodInventory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập kiểm kê cho tất cả các sản phẩm trước khi xuất điều chỉnh..
        /// </summary>
        internal static string GoodInventory3 {
            get {
                return ResourceManager.GetString("GoodInventory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày lấy dữ liệu tồn kho nhỏ hơn ngày hiện tại không được xuất điều chỉnh..
        /// </summary>
        internal static string GoodInventory4 {
            get {
                return ResourceManager.GetString("GoodInventory4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày lấy dữ liệu tồn kho nhỏ hơn ngày hiện tại không được nhập điều chỉnh..
        /// </summary>
        internal static string GoodInventory5 {
            get {
                return ResourceManager.GetString("GoodInventory5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại dữ liệu kiểm kê ngày hôm nay, bạn có muốn lưu đè không ?.
        /// </summary>
        internal static string GoodInventory6 {
            get {
                return ResourceManager.GetString("GoodInventory6", resourceCulture);
            }
        }
    }
}
