//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaleMT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Message Dialog:
        ///Msg.TitleDialog:Notification
        ///Msg.PermissionDialog:You do not have permission to access this function
        ///Msg.Error:Error
        ///Msg.UpdateSuccess:Update success
        ///Msg.EmailNotFound: Email not found
        ///Msg.AmountNotEmpty: Amount not empty!
        ///Msg.DataNotFound: Data not found
        ///Msg.InvoiceNotEmpty: Invoice not empty
        ///Msg.InvoiceExists: Invoice exists!
        ///Msg.MustBeSelected: Please select data
        ///Msg.NoPermissionQty:The quantity is not allowed
        ///Msg.PasswordNotSame: Password not same!
        ///Msg.Mandatory: Required t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Language_es {
            get {
                return ResourceManager.GetString("Language_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Message Dialog
        ///Msg.TitleDialog:​ການ​ແຈ້ງ
        ///Msg.PermissionDialog:ຟັ່ງ​ຊັ່ນ​ນີ້ບໍ່​ອະ​ນຸ​ຍາດ​ໃຫ້​ເຈົ້າ​ເຂົ້າ​ໄດ້
        ///Msg.Error:ຜິດ​ພາດ
        ///Msg.UpdateSuccess:ອັບ​ເດ​ດ​ສຳ​ເລັດ
        ///Msg.EmailNotFound:ບໍ່​ພົບ​ອີ​ເມວ
        ///Msg.DataNotFound:ຈຳ​ນວນບໍ່​ຫວ່າງ
        ///Msg.AmountNotEmpty:ບໍ່​ພົບ​ຂໍ້​ມູນ
        ///Msg.InvoiceNotEmpty:ໃບ​ແຈ້ງ​ລາ​ຄາບໍ່​ຫວ່າງ
        ///Msg.InvoiceExists:ມີ​ໃບ​ແຈ້ງ​ລາ​ຄາ
        ///Msg.MustBeSelected:ກະ​ລຸ​ນາ​ເລືອກ​ຂໍ້​ມູນ
        ///Msg.NoPermissionQty:ປະ​ລິ​ມານບໍ່​ອະ​ນຸ​ຍາດ
        ///Msg.PasswordNotSame:ລະ​ຫັດ​ຜ່ານບໍ່​ຄື​ກັນ
        ///Msg.Mandatory:ຕ້ອງ​ໃສ່​ບ່ອນ​ທີ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Language_lao {
            get {
                return ResourceManager.GetString("Language_lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Message Dialog:
        ///Msg.TitleDialog:Thông báo
        ///Msg.PermissionDialog:Bạn không có quyền truy cập chức năng này
        ///Msg.Error:Thông báo lỗi
        ///Msg.UpdateSuccess: Cập nhật thành công
        ///Msg.EmailNotFound: Không tìm thấy email
        ///Msg.DataNotFound: Không tìm thấy dữ liệu
        ///Msg.AmountNotEmpty: Số tiền không được để trống
        ///Msg.InvoiceNotEmpty: Số hóa đơn không được để trống
        ///Msg.InvoiceExists: Số hóa đơn đã tồn tại
        ///Msg.MustBeSelected: Vui lòng chọn dữ liệu
        ///Msg.NoPermissionQty:Bạn không được phép sửa số lượng
        ///Msg.PasswordNo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Language_vn {
            get {
                return ResourceManager.GetString("Language_vn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #02. Item Return Report 
        ///
        ///ItemReutrn.Title:ITEM RETURN
        ///ItemReutrn.FromDate: FromDate
        ///ItemReutrn.ToDate: ToDate
        ///ItemReutrn.PrintDate: PrintDate
        ///ItemReutrn.TotalQty: Total Qty
        ///ItemReutrn.TotalAmount: Total Amount
        ///ItemReutrn.TotalOther: Total Other
        ///ItemReutrn.Order: No
        ///ItemReutrn.ItemCode: Code Item
        ///ItemReutrn.ItemName: Name Item
        ///ItemReutrn.UOM: UOM
        ///ItemReutrn.Quantity: Quantity
        ///ItemReutrn.Price: Price
        ///ItemReutrn.Amount: Amount
        ///ItemReutrn.AmountReturn: Amt Return
        ///ItemReturn.CAT: CAT
        ///ItemRetur [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Report_es {
            get {
                return ResourceManager.GetString("Report_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #02. Item Return Report :
        ///
        ///ItemReutrn.Title:ກັບ​ຄືນ​ລາຍ​ການ
        ///ItemReutrn.FromDate:ຈາກວັນ​ທີ
        ///ItemReutrn.ToDate:ເຖີງວັນ​ທີ
        ///ItemReutrn.PrintDate:ພິມ​ວັນ​ທີ
        ///ItemReutrn.TotalQty:ລວມ​ປະ​ລິ​ມານ
        ///ItemReutrn.TotalAmount:ລວມ​ຈຳ​ນວນ​ທັງ​ໝົດ
        ///ItemReutrn.TotalOther:​ລວມ​ຈຳ​ນວນ​ອື່ນໆ​ທັງ​ໝົດ
        ///ItemReutrn.Order:ບໍ່
        ///ItemReutrn.ItemCode:ລາຍ​ການ​ລະ​ຫັດ
        ///ItemReutrn.ItemName:ລາຍ​ການ​ຊື່
        ///ItemReutrn.UOM: UOM
        ///ItemReutrn.Quantity:ປະ​ລິ​ມານ
        ///ItemReutrn.Price:​ລາ​ຄາ
        ///ItemReutrn.Amount:ຈຳ​ນວນ
        ///ItemReutrn.AmountReturn:ກັບ​ຄືນ​ຈຳ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Report_lao {
            get {
                return ResourceManager.GetString("Report_lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #02. Item Return Report 
        ///
        ///ItemReutrn.Title:HÀNG TRẢ LẠI
        ///ItemReutrn.FromDate: Từ ngày
        ///ItemReutrn.ToDate: Đến ngày
        ///ItemReutrn.PrintDate: Ngày in
        ///ItemReutrn.TotalQty: Tổng SL
        ///ItemReutrn.TotalAmount: Tổng TT
        ///ItemReutrn.TotalOther: Tổng TTL
        ///ItemReutrn.Order: STT
        ///ItemReutrn.ItemCode: Mã SP
        ///ItemReutrn.ItemName: Tên SP
        ///ItemReutrn.UOM: ĐVT
        ///ItemReutrn.Quantity: SL
        ///ItemReutrn.Price: ĐG
        ///ItemReutrn.Amount: T.Tiền
        ///ItemReutrn.AmountReturn: Tiền T.lại
        ///ItemReturn.CAT: Loại 
        ///ItemReturn.CodeReturn: Mã trả
        ///I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Report_vn {
            get {
                return ResourceManager.GetString("Report_vn", resourceCulture);
            }
        }
    }
}
