//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMTInterfaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsfExportManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsfExportManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaleMTInterfaces.Properties.rsfExportManagement", typeof(rsfExportManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hóa đơn không chính xác..
        /// </summary>
        internal static string cNgayHD {
            get {
                return ResourceManager.GetString("cNgayHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số nội bộ không chính xác..
        /// </summary>
        internal static string cSoNoiBo {
            get {
                return ResourceManager.GetString("cSoNoiBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số PO không chính xác..
        /// </summary>
        internal static string cSoPo {
            get {
                return ResourceManager.GetString("cSoPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập diễn giải điều chỉnh..
        /// </summary>
        internal static string DienGiai {
            get {
                return ResourceManager.GetString("DienGiai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho của sản phẩm có mã {0} không đủ để xuất hàng, vui lòng kiểm tra lại..
        /// </summary>
        internal static string Export1 {
            get {
                return ResourceManager.GetString("Export1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn số &apos;{0}&apos; chưa được nhập hàng, không thể trả hàng của hóa đơn này..
        /// </summary>
        internal static string Export10 {
            get {
                return ResourceManager.GetString("Export10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có {0} dòng dữ liệu sản phẩm không hợp lệ, bạn có muốn tiếp tục lưu hay không?.
        /// </summary>
        internal static string Export11 {
            get {
                return ResourceManager.GetString("Export11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm có mã {0} có số lượng trả hàng nhiều hơn số lượng nhập hàng..
        /// </summary>
        internal static string Export2 {
            get {
                return ResourceManager.GetString("Export2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm có mã {0} không có trong danh sách sản phẩm của hóa đơn nhập hàng {1}.
        /// </summary>
        internal static string Export3 {
            get {
                return ResourceManager.GetString("Export3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất hàng thành công..
        /// </summary>
        internal static string Export4 {
            get {
                return ResourceManager.GetString("Export4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        internal static string Export5 {
            get {
                return ResourceManager.GetString("Export5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa đợt xuất hàng?.
        /// </summary>
        internal static string Export6 {
            get {
                return ResourceManager.GetString("Export6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa đợt xuất hàng thành công..
        /// </summary>
        internal static string Export7 {
            get {
                return ResourceManager.GetString("Export7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu xuất hàng..
        /// </summary>
        internal static string Export8 {
            get {
                return ResourceManager.GetString("Export8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhập không hợp lệ..
        /// </summary>
        internal static string NgayNhap {
            get {
                return ResourceManager.GetString("NgayNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập sản phẩm..
        /// </summary>
        internal static string SanPham {
            get {
                return ResourceManager.GetString("SanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số hóa đơn..
        /// </summary>
        internal static string SoHD {
            get {
                return ResourceManager.GetString("SoHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số nội bộ..
        /// </summary>
        internal static string SoNoiBo {
            get {
                return ResourceManager.GetString("SoNoiBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số PO..
        /// </summary>
        internal static string SoPo {
            get {
                return ResourceManager.GetString("SoPo", resourceCulture);
            }
        }
    }
}
