//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMTInterfaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsfImportManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsfImportManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaleMTInterfaces.Properties.rsfImportManagement", typeof(rsfImportManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa đợt nhập hàng?.
        /// </summary>
        internal static string Import1 {
            get {
                return ResourceManager.GetString("Import1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập sản phẩm.
        /// </summary>
        internal static string Import10 {
            get {
                return ResourceManager.GetString("Import10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có {0} dòng dữ liệu sản phẩm không hợp lệ, bạn có muốn tiếp tục lưu hay không?.
        /// </summary>
        internal static string Import11 {
            get {
                return ResourceManager.GetString("Import11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu nhập hàng..
        /// </summary>
        internal static string Import12 {
            get {
                return ResourceManager.GetString("Import12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá nhập hàng thành công..
        /// </summary>
        internal static string Import2 {
            get {
                return ResourceManager.GetString("Import2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhập hàng thành công..
        /// </summary>
        internal static string Import3 {
            get {
                return ResourceManager.GetString("Import3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhập hàng thành công..
        /// </summary>
        internal static string Import4 {
            get {
                return ResourceManager.GetString("Import4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số hóa đơn..
        /// </summary>
        internal static string Import5 {
            get {
                return ResourceManager.GetString("Import5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số nội bộ..
        /// </summary>
        internal static string Import6 {
            get {
                return ResourceManager.GetString("Import6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số PO.
        /// </summary>
        internal static string Import7 {
            get {
                return ResourceManager.GetString("Import7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhập không hợp lệ.
        /// </summary>
        internal static string Import8 {
            get {
                return ResourceManager.GetString("Import8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hóa đơn đã tồn tại.
        /// </summary>
        internal static string Import9 {
            get {
                return ResourceManager.GetString("Import9", resourceCulture);
            }
        }
    }
}
