//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMTInterfaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsfInventoryImport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsfInventoryImport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaleMTInterfaces.Properties.rsfInventoryImport", typeof(rsfInventoryImport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tập tin &apos;{0}&apos;..
        /// </summary>
        internal static string Inventory1 {
            get {
                return ResourceManager.GetString("Inventory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng mở tập tin để import..
        /// </summary>
        internal static string Inventory2 {
            get {
                return ResourceManager.GetString("Inventory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn sheet..
        /// </summary>
        internal static string Inventory3 {
            get {
                return ResourceManager.GetString("Inventory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template chưa đúng định dạng..
        /// </summary>
        internal static string Inventory4 {
            get {
                return ResourceManager.GetString("Inventory4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có {0} mã hàng không thể import, bạn có muốn xem danh sách không?.
        /// </summary>
        internal static string Inventory6 {
            get {
                return ResourceManager.GetString("Inventory6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công.
        /// </summary>
        internal static string Inventory7 {
            get {
                return ResourceManager.GetString("Inventory7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn lưu dữ liệu đặt hàng !.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập sản phẩm ..
        /// </summary>
        internal static string Order1 {
            get {
                return ResourceManager.GetString("Order1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công !.
        /// </summary>
        internal static string Order2 {
            get {
                return ResourceManager.GetString("Order2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công !.
        /// </summary>
        internal static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
    }
}
