//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMTInterfaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsfReceipts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsfReceipts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaleMTInterfaces.Properties.rsfReceipts", typeof(rsfReceipts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa hóa đơn {0} không?.
        /// </summary>
        internal static string Receipt1 {
            get {
                return ResourceManager.GetString("Receipt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa dữ liệu in hóa đơn đỏ hay không?.
        /// </summary>
        internal static string Receipt10 {
            get {
                return ResourceManager.GetString("Receipt10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hóa đơn nào..
        /// </summary>
        internal static string Receipt11 {
            get {
                return ResourceManager.GetString("Receipt11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xóa hóa đơn..
        /// </summary>
        internal static string Receipt12 {
            get {
                return ResourceManager.GetString("Receipt12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn hóa đơn mua hàng của cùng một khách hàng..
        /// </summary>
        internal static string Receipt13 {
            get {
                return ResourceManager.GetString("Receipt13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn mua hàng này đã in hóa đơn đỏ..
        /// </summary>
        internal static string Receipt14 {
            get {
                return ResourceManager.GetString("Receipt14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hàng hóa không được nhiều hơn 16 dòng..
        /// </summary>
        internal static string Receipt15 {
            get {
                return ResourceManager.GetString("Receipt15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số hóa đơn đỏ.
        /// </summary>
        internal static string Receipt2 {
            get {
                return ResourceManager.GetString("Receipt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã số thuế.
        /// </summary>
        internal static string Receipt3 {
            get {
                return ResourceManager.GetString("Receipt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên đơn vị.
        /// </summary>
        internal static string Receipt4 {
            get {
                return ResourceManager.GetString("Receipt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ.
        /// </summary>
        internal static string Receipt5 {
            get {
                return ResourceManager.GetString("Receipt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền hàng hóa đơn phải lớn hơn 0.
        /// </summary>
        internal static string Receipt6 {
            get {
                return ResourceManager.GetString("Receipt6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền in hóa đơn ({0}) khác tổng tiền mua hàng ({1}), bạn có muốn tiếp tục in hay không?.
        /// </summary>
        internal static string Receipt7 {
            get {
                return ResourceManager.GetString("Receipt7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các sản phẩm in trong hóa đơn phải cùng ngành hàng.
        /// </summary>
        internal static string Receipt8 {
            get {
                return ResourceManager.GetString("Receipt8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn đỏ có số &apos;{0}&apos; đã được in..
        /// </summary>
        internal static string Receipt9 {
            get {
                return ResourceManager.GetString("Receipt9", resourceCulture);
            }
        }
    }
}
